# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - SparkLight

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Configura o Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '7.4.2' 

      - name: Build with Gradle
        run: ./gradlew build  

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: war-app
          path: build/libs/*.war  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: war-app

      # Faz o deploy no Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SparkLight'  # Nome do seu Web App no Azure
          slot-name: 'Production'  # Se você usar slots de produção
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  
          package: '*.war'  
